/** Optimized WebP paths — generated by scripts/optimize-images.js */
const opt = (name: string) => `/images/optimized/${name}.webp`;

export const IMAGES = {
  hero: {
    slide1: opt("KING1010585"),
    slide2: opt("KING6653"),
  },
  aboutPreview: opt("IMG_2650"),
  aboutBio: opt("IMG_2502"),
  gbeduHero: opt("KING1010571"),
  gbeduFeature: opt("KING6613"),
  gbeduExperience: opt("KING6614"),
  workWithKing: opt("IMG_2789"),
  pressAccent: opt("IMG_22241"),
  gallery: [
    {
      src: opt("KING1010571"),
      alt: "The full Gbèdu ensemble on stage with blue curtain backdrop at Afro Jazz Fest",
    },
    {
      src: opt("KING6613"),
      alt: "Wide shot of the Gbèdu orchestra performing under stage lights",
    },
    {
      src: opt("KING1010517"),
      alt: "Close-up of a Gbèdu ensemble musician during live performance",
    },
    {
      src: opt("KING1010465"),
      alt: "Audience perspective of the Gbèdu performance at Afro Jazz Fest",
    },
    {
      src: opt("KING1010524"),
      alt: "King Udofia conducting the Gbèdu ensemble on stage",
    },
    {
      src: opt("KING1010583"),
      alt: "Gbèdu musicians in performance with vibrant stage lighting",
    },
  ],
  work: {
    gbedu: opt("KING6613"),
    stampede: opt("IMG_2438"),
    disney: opt("IMG_2224"),
    titilope: opt("IMG_2543"),
    cjo: opt("IMG_2533"),
    "femi-leye": opt("IMG_2812"),
    key30: opt("IMG_2523"),
    "ethnic-festivals": opt("IMG_2442"),
  },
} as const;

export const IMAGE_ALTS = {
  heroSlide1:
    "King Udofia performing live with the Gbèdu ensemble on stage",
  heroSlide2:
    "Wide stage shot of King Udofia and the Gbèdu orchestra in performance",
  aboutPreview:
    "King Udofia portrait for about section",
  aboutBio:
    "King Udofia studio portrait for biography section",
  gbeduHero:
    "The Gbèdu Afro-jazz orchestral ensemble on stage with blue curtains",
  gbeduFeature:
    "Gbèdu live performance wide stage shot",
  gbeduExperience:
    "Gbèdu ensemble in performance at Afro Jazz Fest",
  workWithKing:
    "King Udofia in white jacket, studio portrait",
  pressAccent:
    "King Udofia professional portrait for press and media",
} as const;
